# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcd34f6ec2df76b6de5322c5c828230bda22e920d06b7352783219f31a7e93ce1557a49fc5f5f549943a39e87584319cab67d1571f5bf53b3adba8ab9db2bded

test:
  secret_key_base: 8dd908b77d244d6b8d4ca62347d997403ecf24b2b9e77b97fd346eca5e1f75fc93656bbc65b3786dc436111f10c7e7439f4b8f9776bdad2e0b6f3b70e8a5f82e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
